trigger:
- main

pool:
  name: AgentPool-Laptop   # your self-hosted agent pool

steps:
# Step 1: Setup venv and install dependencies
- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Setup venv and install dependencies'

# - script: robocop check
#   workingDirectory: '$(Build.SourcesDirectory)\Test'
#   displayName: 'Run Robocop quality checks in Test folder'

- script: robot
  workingDirectory: '$(Build.SourcesDirectory)\Test'
  displayName: 'Run Robot Framework tests in Test folder'
