# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: AgentPool-Laptop

steps:
- script: |
    python --version || (
      echo "'python' is not recognized as an internal or external command"
      choco install python --version=3.11.9 -y
    )
  displayName: 'Check and Install Python if missing'
